spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scheduler_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  docker:
    compose:
      enabled: false